### ISSUE TITLE
Pushing data from the Pi to the site

### ISSUE THREAD

**Issue by dbrill** [dbrill/FlyThePi#3]
Ok so here's my newest plan for solving this issue:

We host the website from our Raspberry-Pi, run a cron job on our Pi to push it's data (height, location...etc.) every <some time interval> to a local file, have our site constantly read from that file and update it's displayed data accordingly.

**Comment by CaptainAtlas** [comment]
Assuming the website can be served from a local address that doesn't have to be resolved by DNS, this would be viable.

**Comment by CaptainAtlas** [comment]
@dbrill and @Bhawth assigned to this issue.

**Comment by dbrill** [comment]
Because our website is being hosted by heroku, Brian and I have decided that we can run a cron job to every <some interval of time> run the gpsd, populate from output.txt file with relevant data that our html file will pull from, and then push the updated file to heroku via the command line. We're gonna need to spend some time with Dan until I get my Raspberry Pi to see how data is being populated in order to gracefully populate the output.txt file. Shouldn't be a problem at all once we know what we're working with.

**Comment by CaptainAtlas** [comment]
Are we still considering this? Or should we host everything on the pi?

**Comment by CaptainAtlas** [comment]
Assuming pushing to heroku for now.... open a new issue if we should change this 👍
